import type { CharacterData } from '../types'

// 第一版 6 個角色；最終版 12+（加角色 = 加一筆資料 + art.ts 一段繪製）。
export const CHARACTERS: CharacterData[] = [
  {
    id: 'warrior_sweetpotato',
    name: '戰士地瓜',
    description: '皮厚扛線的前排。救援隊友時獲得護盾，衝進怪堆就是他的工作。',
    role: 'tank',
    baseStats: { maxHp: 140, armor: 4, moveSpeed: 165, damage: 1.05, attackSpeed: 0.95, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.6 },
    passive: { description: '近戰武器傷害 +20%；救援隊友時獲得 30 點護盾', mods: {}, effect: 'meleeBoostRescueShield' },
    active: { id: 'charge', name: '衝撞', description: '向拖曳方向衝刺，擊退並傷害路徑上的怪物', cooldown: 8, params: { dist: 300, damage: 25, knockback: 220 } },
    startWeapons: ['hammer', 'spin_axe', 'pea_gun'],
    rarity: 'common',
    palette: ['#c97b3d', '#a35426', '#7bc043'],
  },
  {
    id: 'gunner_potato',
    name: '槍手馬鈴薯',
    description: '標準遠程輸出。攻速快射程遠，但皮薄，站位是生命。',
    role: 'dps',
    baseStats: { maxHp: 90, armor: 0, moveSpeed: 175, damage: 1.1, attackSpeed: 1.15, critChance: 0.05, critDamage: 1.5, pickupRange: 75, regen: 0.2 },
    passive: { description: '遠程武器射程 +15%', effect: 'rangedRangeBoost' },
    active: { id: 'rapidfire', name: '火力全開', description: '5 秒內攻擊速度 +80%', cooldown: 14, params: { duration: 5, atkBoost: 0.8 } },
    startWeapons: ['pea_gun', 'knife', 'drone'],
    rarity: 'common',
    palette: ['#d9b380', '#b8905c', '#5c4a2e'],
  },
  {
    id: 'medic_radish',
    name: '醫生蘿蔔',
    description: '隊伍的心臟。靠近隊友緩慢回血、救援飛快，自傷害偏低。',
    role: 'support',
    baseStats: { maxHp: 105, armor: 1, moveSpeed: 170, damage: 0.85, attackSpeed: 1.0, critChance: 0.03, critDamage: 1.5, pickupRange: 85, regen: 0.8 },
    passive: { description: '160 範圍內隊友每秒回 1.2 HP；救援速度 +40%', effect: 'auraHealFastRescue' },
    active: { id: 'healzone', name: '治療圈', description: '放置治療區 6 秒，站在裡面每秒回 6 HP', cooldown: 16, params: { duration: 6, radius: 130, hps: 6 } },
    startWeapons: ['heal_orb', 'pea_gun', 'ice_shard'],
    rarity: 'common',
    palette: ['#e85d6a', '#c93a4d', '#7bc043'],
  },
  {
    id: 'engineer_onion',
    name: '工程洋蔥',
    description: '陣地戰大師。工程武器傷害提升、砲塔地雷冷卻更短。',
    role: 'engineer',
    baseStats: { maxHp: 110, armor: 2, moveSpeed: 160, damage: 0.95, attackSpeed: 1.0, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.4 },
    passive: { description: '工程武器傷害 +25%，冷卻 -15%', effect: 'engineerBoost' },
    active: { id: 'turret', name: '臨時砲塔', description: '放置一座自動攻擊砲塔（10 秒）', cooldown: 18, params: { duration: 10, damage: 6, fireCd: 0.5, range: 320 } },
    startWeapons: ['turret_gun', 'mine', 'pea_gun'],
    rarity: 'common',
    palette: ['#e8d5a3', '#c9a86a', '#8a6d3b'],
  },
  {
    id: 'mage_yam',
    name: '冰法番薯',
    description: '控場法師。攻擊帶減速/冰凍，範圍法術效果更大。',
    role: 'control',
    baseStats: { maxHp: 95, armor: 0, moveSpeed: 168, damage: 1.0, attackSpeed: 1.0, critChance: 0.04, critDamage: 1.5, pickupRange: 75, regen: 0.3 },
    passive: { description: '所有攻擊 12% 機率減速敵人；範圍效果 +20%', mods: { area: 0.2 }, effect: 'chillTouch' },
    active: { id: 'frostnova', name: '冰霜爆發', description: '凍結 220 範圍內敵人 2.5 秒並造成傷害', cooldown: 15, params: { radius: 220, damage: 18, freeze: 2.5 } },
    startWeapons: ['ice_shard', 'fireball', 'lightning'],
    rarity: 'common',
    palette: ['#8f6ad1', '#6a44b0', '#a8e0ff'],
  },
  {
    id: 'gambler_taro',
    name: '賭徒芋頭',
    description: '高風險高報酬。暴擊超高、升級可能開出更稀有，也可能翻出詛咒。',
    role: 'gambler',
    baseStats: { maxHp: 100, armor: 0, moveSpeed: 172, damage: 1.0, attackSpeed: 1.0, critChance: 0.15, critDamage: 1.7, pickupRange: 75, regen: 0.3 },
    passive: { description: '升級選項 +25% 機率升一階稀有度，但商店可能混入詛咒選項', effect: 'gamblerLuck' },
    active: { id: 'fateflip', name: '命運翻牌', description: '隨機獲得一個強力增益，或一個小小的懲罰', cooldown: 12, params: {} },
    startWeapons: ['knife', 'fireball', 'poison_flask'],
    rarity: 'common',
    palette: ['#b58fd1', '#8f63b8', '#e0c2f0'],
  },
]

export const CHARACTER_MAP = new Map(CHARACTERS.map(c => [c.id, c]))
