import type { CharacterData } from '../types'

// 第一版 6 個角色；最終版 12+（加角色 = 加一筆資料 + art.ts 一段繪製）。
export const CHARACTERS: CharacterData[] = [
  {
    id: 'warrior_sweetpotato',
    name: '戰士地瓜',
    description: '厚甲前排。舉盾衝鋒時幾乎免疫傷害、把怪物一路撞飛。血厚甲高但攻速慢。',
    role: 'tank',
    baseStats: { maxHp: 158, armor: 5, moveSpeed: 162, damage: 1.0, attackSpeed: 0.88, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.7 },
    passive: { description: '近戰武器傷害 +20%；救援隊友時獲得 30 點護盾', mods: {}, effect: 'meleeBoostRescueShield' },
    active: { id: 'bulwark', name: '盾牌衝鋒', description: '舉盾向前推進 2 秒：減傷 90%、獲得護盾，撞飛沿路怪物', cooldown: 12, params: { duration: 2, dr: 0.9, speed: 135, damage: 20, knockback: 320, shield: 40 } },
    startWeapons: ['w_sword', 'w_greatsword', 'w_spear', 'spin_axe', 'hammer'],
    rarity: 'common',
    palette: ['#c97b3d', '#a35426', '#7bc043'],
  },
  {
    id: 'gunner_potato',
    name: '槍手馬鈴薯',
    description: '連射型遠程輸出。攻速極快、射程遠，但皮薄，站位是生命。',
    role: 'dps',
    baseStats: { maxHp: 84, armor: 0, moveSpeed: 180, damage: 1.05, attackSpeed: 1.28, critChance: 0.05, critDamage: 1.5, pickupRange: 78, regen: 0.2 },
    passive: { description: '遠程武器射程 +15%', effect: 'rangedRangeBoost' },
    active: { id: 'rapidfire', name: '火力全開', description: '5 秒內攻擊速度 +80%', cooldown: 14, params: { duration: 5, atkBoost: 0.8 } },
    startWeapons: ['pea_gun', 'g_sniper', 'g_shotgun', 'g_smg', 'g_minigun'],
    rarity: 'common',
    palette: ['#d9b380', '#b8905c', '#5c4a2e'],
  },
  {
    id: 'medic_radish',
    name: '醫生蘿蔔',
    description: '隊伍的心臟。靠近隊友緩慢回血、救援飛快、自身回血快，但輸出低。',
    role: 'support',
    baseStats: { maxHp: 104, armor: 1, moveSpeed: 172, damage: 0.78, attackSpeed: 1.0, critChance: 0.03, critDamage: 1.5, pickupRange: 90, regen: 1.0 },
    passive: { description: '160 範圍內隊友每秒回 1.2 HP；救援速度 +40%', effect: 'auraHealFastRescue' },
    active: { id: 'healzone', name: '治療圈', description: '放置治療區 6 秒，站在裡面每秒回 6 HP', cooldown: 16, params: { duration: 6, radius: 130, hps: 6 } },
    startWeapons: ['heal_orb', 'm_needle', 'm_cross', 'm_biozone', 'm_drone'],
    rarity: 'common',
    palette: ['#e85d6a', '#c93a4d', '#7bc043'],
  },
  {
    id: 'engineer_onion',
    name: '工程洋蔥',
    description: '陣地戰大師。工程武器傷害提升、砲塔地雷冷卻更短，血量中上、移動偏慢。',
    role: 'engineer',
    baseStats: { maxHp: 118, armor: 2, moveSpeed: 162, damage: 0.95, attackSpeed: 1.0, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.4 },
    passive: { description: '工程武器傷害 +25%，冷卻 -15%', effect: 'engineerBoost' },
    active: { id: 'turret', name: '臨時砲塔', description: '放置一座自動攻擊砲塔（10 秒）', cooldown: 18, params: { duration: 10, damage: 6, fireCd: 0.5, range: 320 } },
    startWeapons: ['turret_gun', 'mine', 'drone', 'e_laser', 'e_flame'],
    rarity: 'common',
    palette: ['#e8d5a3', '#c9a86a', '#8a6d3b'],
  },
  {
    id: 'mage_yam',
    name: '冰法番薯',
    description: '控場法師。攻擊帶減速/冰凍、範圍法術更大、單發傷害高，但血薄。',
    role: 'control',
    baseStats: { maxHp: 86, armor: 0, moveSpeed: 164, damage: 1.15, attackSpeed: 0.95, critChance: 0.04, critDamage: 1.5, pickupRange: 75, regen: 0.3 },
    passive: { description: '所有攻擊 12% 機率減速敵人；範圍效果 +20%', mods: { area: 0.2 }, effect: 'chillTouch' },
    active: { id: 'frostnova', name: '冰霜爆發', description: '凍結 220 範圍內敵人 2.5 秒並造成傷害', cooldown: 15, params: { radius: 220, damage: 18, freeze: 2.5 } },
    startWeapons: ['ice_shard', 'fireball', 'lightning', 'y_orb', 'y_frost'],
    rarity: 'common',
    palette: ['#8f6ad1', '#6a44b0', '#a8e0ff'],
  },
  {
    id: 'gambler_taro',
    name: '賭徒芋頭',
    description: '高風險高報酬。暴擊超高、暴傷驚人，升級可能開出更稀有，也可能翻出詛咒。',
    role: 'gambler',
    baseStats: { maxHp: 96, armor: 0, moveSpeed: 172, damage: 1.0, attackSpeed: 1.0, critChance: 0.18, critDamage: 1.8, pickupRange: 75, regen: 0.3 },
    passive: { description: '升級選項 +25% 機率升一階稀有度，但商店可能混入詛咒選項', effect: 'gamblerLuck' },
    active: { id: 'fateflip', name: '命運翻牌', description: '隨機獲得一個強力增益，或一個小小的懲罰', cooldown: 12, params: {} },
    startWeapons: ['t_dice', 't_cards', 't_coin', 't_orbit', 't_roulette'],
    rarity: 'common',
    palette: ['#b58fd1', '#8f63b8', '#e0c2f0'],
  },
  {
    id: 'assassin_sprout',
    name: '刺客豆芽',
    description: '暴擊流刺客。全場最快、暴擊爆表，但血薄如紙，靠身法吃飯。',
    role: 'dps',
    baseStats: { maxHp: 72, armor: 0, moveSpeed: 196, damage: 1.05, attackSpeed: 1.22, critChance: 0.24, critDamage: 1.85, pickupRange: 80, regen: 0.2 },
    passive: { description: '暴擊率額外 +8%、暴擊傷害 +30%', mods: { critChance: 0.08, critDamage: 0.3 } },
    active: { id: 'charge', name: '瞬步斬', description: '朝拖曳方向瞬移，斬擊路徑上的敵人', cooldown: 7, params: { dist: 320, damage: 30, knockback: 150 } },
    startWeapons: ['knife', 'a_fan', 'a_shuriken', 'poison_flask', 'a_drone'],
    unlockCondition: '通關快速模式',
    rarity: 'rare',
    palette: ['#c5e1a5', '#7cb342', '#33691e'],
  },
  {
    id: 'samurai_tomato',
    name: '武士番茄',
    description: '拔刀流劍客。全隊最高單發攻擊力、暴傷驚人，居合斬瞬間突進斬穿敵陣，但血量偏低。',
    role: 'dps',
    baseStats: { maxHp: 84, armor: 1, moveSpeed: 176, damage: 1.35, attackSpeed: 0.95, critChance: 0.1, critDamage: 1.8, pickupRange: 76, regen: 0.3 },
    passive: { description: '拔刀術：暴擊傷害 +40%、近戰傷害 +15%', mods: { critDamage: 0.4 } },
    active: { id: 'whirlslash', name: '旋風斬', description: '旋身以刀氣斬擊四周敵人，造成大量傷害並擊退', cooldown: 8, params: { radius: 190, damage: 45, knockback: 200 } },
    startWeapons: ['s_iai', 's_katana', 's_kunai', 's_wave', 's_odachi'],
    rarity: 'rare',
    palette: ['#e2402f', '#a5231b', '#5fae3a'],
  },
  {
    id: 'cactus_thorns',
    name: '反甲仙人掌',
    description: '荊棘坦克。血厚甲高、渾身尖刺——近戰攻擊他的怪物自己也會受傷。移動慢、輸出偏低，但耐打。',
    role: 'tank',
    baseStats: { maxHp: 176, armor: 7, moveSpeed: 158, damage: 0.82, attackSpeed: 0.9, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.6 },
    passive: { description: '尖刺反甲：近戰攻擊你的怪物受到反傷（依你的傷害成長）', effect: 'thornsReflect' },
    active: { id: 'thornsNova', name: '荊棘爆發', description: '向四周射出尖刺，重傷並擊退周圍敵人，並獲得護盾', cooldown: 12, params: { radius: 190, damage: 34, knockback: 260, shield: 55 } },
    startWeapons: ['c_gauntlet', 'c_whip', 'c_shield', 'c_spikes', 'c_seed'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#4c9a52', '#2f6b34', '#8bc34a'],
  },
  {
    id: 'monk_tofu',
    name: '武僧豆腐',
    description: '五形拳法的武術家。攻速快、身法靈活，拳/掌/腿/棍/氣功五種功夫各有打法，血量中等。',
    role: 'dps',
    baseStats: { maxHp: 100, armor: 1, moveSpeed: 184, damage: 1.1, attackSpeed: 1.2, critChance: 0.08, critDamage: 1.6, pickupRange: 76, regen: 0.4 },
    passive: { description: '拳意通神：攻速 +12%、移速 +4%', mods: { attackSpeed: 0.12, moveSpeed: 0.04 } },
    active: { id: 'palmquake', name: '震地掌', description: '拍地震盪，重擊、擊退並暈眩周圍敵人 1.5 秒', cooldown: 10, params: { radius: 180, damage: 26, knockback: 240, stun: 1.5 } },
    startWeapons: ['k_fist', 'k_palm', 'k_kick', 'k_staff', 'k_qi'],
    unlockCondition: '通關快速模式',
    rarity: 'rare',
    palette: ['#f5f0e0', '#d4a574', '#e0733a'],
  },
  {
    id: 'durian_spike',
    name: '暴刺榴槤',
    description: '渾身尖刺的中距離刺手。主動技「蓄刺爆發」按住蓄力越久、放開時往全場噴射的尖刺越大越痛，最高 1.5 倍。',
    role: 'dps',
    baseStats: { maxHp: 106, armor: 2, moveSpeed: 172, damage: 1.1, attackSpeed: 1.05, critChance: 0.06, critDamage: 1.6, pickupRange: 76, regen: 0.4 },
    passive: { description: '滿身是刺：範圍效果 +15%、傷害 +8%', mods: { area: 0.15, damage: 0.08 } },
    active: { id: 'spikecharge', name: '蓄刺爆發', description: '按住蓄力（最多 2 秒），放開時往四周噴射尖刺——蓄越久範圍越大、傷害最高 1.5 倍，並留下尖刺區持續傷害', cooldown: 12, params: { radius: 300, maxRadius: 1700, damage: 30, knockback: 200, maxHold: 2, zoneDps: 8, zoneDur: 1.5 } },
    startWeapons: ['d_thornshot', 'd_spikefan', 'd_caltrop', 'd_spikeorbit', 'd_barb'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#f0a83e', '#e0512f', '#4a4258'],
  },
  {
    id: 'hemp_mystic',
    name: '迷幻大麻',
    description: '玩弄心智的孢子幻術師。攻擊會噴出迷幻孢子，讓害蟲「嗑到」而神智不清；主動技「迷幻孢子」灑出一片幻覺雲，範圍內的怪物陷入混亂、亂晃且不再攻擊。血薄，靠控場活命。',
    role: 'control',
    baseStats: { maxHp: 88, armor: 0, moveSpeed: 168, damage: 1.12, attackSpeed: 1.0, critChance: 0.05, critDamage: 1.55, pickupRange: 82, regen: 0.3 },
    passive: { description: '孢子沾染：攻擊 15% 機率使敵人陷入迷幻（混亂 2 秒）；範圍效果 +20%', mods: { area: 0.2 }, effect: 'hazeTouch' },
    active: { id: 'hallucinate', name: '迷幻孢子', description: '噴出一片迷幻孢子雲——範圍內敵人立即陷入混亂（亂走、不攻擊）並受傷；孢子雲留存數秒，持續讓踏入的怪物混亂', cooldown: 16, params: { radius: 240, damage: 14, confuse: 4, cloudDur: 5, cloudRadius: 190 } },
    startWeapons: ['h_spore', 'h_pollen', 'h_smoke', 'h_mirage', 'h_haze'],
    unlockCondition: '通關無盡模式',
    rarity: 'epic',
    palette: ['#6d5aa8', '#e05fd0', '#7cc36a'],
  },
]

export const CHARACTER_MAP = new Map(CHARACTERS.map(c => [c.id, c]))
