import type { CharacterData } from '../types'

// 第一版 6 個角色；最終版 12+（加角色 = 加一筆資料 + art.ts 一段繪製）。
export const CHARACTERS: CharacterData[] = [
  {
    id: 'warrior_sweetpotato',
    name: '盾衛地瓜',
    description: '以盾為武、以身為牆的盾之勇者。無論擲盾、盾擊還是舉盾衝鋒，攻守全在一面盾上；受擊越多、反擊越猛。是全隊最可靠的前排肉盾。',
    role: 'tank',
    baseStats: { maxHp: 158, armor: 5, moveSpeed: 162, damage: 1.0, attackSpeed: 0.88, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.7 },
    passive: { description: '盾之勇者：近戰武器傷害 +20%；救援隊友時獲得 30 點護盾', mods: {}, effect: 'meleeBoostRescueShield' },
    active: { id: 'bulwark', name: '盾之壁', description: '舉盾向前推進 2 秒：減傷 90%、獲得護盾，撞飛沿路怪物', cooldown: 8, params: { duration: 2, dr: 0.9, speed: 135, damage: 20, knockback: 320, shield: 40 } },
    slots: 4,
    exclusiveGear: true,
    slotLabel: '盾技',
    affinityTags: ['melee', 'heavy', 'knockback'],
    startWeapons: ['w_sword', 'sw_bash', 'sw_thornguard'],
    rarity: 'common',
    palette: ['#c97b3d', '#a35426', '#7bc043'],
  },
  {
    id: 'gunner_potato',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '槍手馬鈴薯',
    description: '連射型遠程輸出。攻速極快、射程遠，但皮薄，站位是生命。',
    role: 'dps',
    baseStats: { maxHp: 84, armor: 0, moveSpeed: 180, damage: 1.05, attackSpeed: 1.28, critChance: 0.05, critDamage: 1.5, pickupRange: 78, regen: 0.2 },
    passive: { description: '遠程武器射程 +15%', effect: 'rangedRangeBoost' },
    active: { id: 'rapidfire', name: '火力全開', description: '5 秒內攻擊速度 +80%', cooldown: 12, params: { duration: 5, atkBoost: 0.8 } },
    affinityTags: ['bullet', 'rapid', 'spread'],
    startWeapons: ['pea_gun', 'g_shotgun', 'g_smg'],
    rarity: 'common',
    palette: ['#d9b380', '#b8905c', '#5c4a2e'],
  },
  {
    id: 'medic_radish',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '醫生蘿蔔',
    description: '隊伍的心臟。靠近隊友緩慢回血、救援飛快、自身回血快，但輸出低。',
    role: 'support',
    baseStats: { maxHp: 104, armor: 1, moveSpeed: 172, damage: 0.78, attackSpeed: 1.0, critChance: 0.03, critDamage: 1.5, pickupRange: 90, regen: 1.0 },
    passive: { description: '160 範圍內隊友每秒回 1.2 HP；救援速度 +40%', effect: 'auraHealFastRescue' },
    active: { id: 'healzone', name: '治療圈', description: '放置治療區 6 秒，站在裡面每秒回 6 HP', cooldown: 13, params: { duration: 6, radius: 130, hps: 6 } },
    affinityTags: ['support', 'heal', 'summon'],
    startWeapons: ['heal_orb', 'm_needle', 'drone'],
    rarity: 'common',
    palette: ['#e85d6a', '#c93a4d', '#7bc043'],
  },
  {
    id: 'engineer_onion',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '工程洋蔥',
    description: '陣地戰大師。工程武器傷害提升、砲塔地雷冷卻更短，血量中上、移動偏慢。',
    role: 'engineer',
    baseStats: { maxHp: 118, armor: 2, moveSpeed: 162, damage: 0.95, attackSpeed: 1.0, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.4 },
    passive: { description: '工程武器傷害 +25%，冷卻 -15%', effect: 'engineerBoost' },
    active: { id: 'turret', name: '臨時砲塔', description: '放置一座自動攻擊砲塔（10 秒）', cooldown: 16, params: { duration: 10, damage: 6, fireCd: 0.5, range: 320 } },
    affinityTags: ['engineer', 'summon', 'explosive'],
    startWeapons: ['turret_gun', 'mine', 'e_flame'],
    rarity: 'common',
    palette: ['#e8d5a3', '#c9a86a', '#8a6d3b'],
  },
  {
    id: 'mage_yam',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '冰法番薯',
    description: '控場法師。攻擊帶減速/冰凍、範圍法術更大、單發傷害高，但血薄。',
    role: 'control',
    baseStats: { maxHp: 86, armor: 0, moveSpeed: 164, damage: 1.15, attackSpeed: 0.95, critChance: 0.04, critDamage: 1.5, pickupRange: 75, regen: 0.3 },
    passive: { description: '所有攻擊 12% 機率減速敵人；範圍效果 +20%', mods: { area: 0.2 }, effect: 'chillTouch' },
    active: { id: 'frostnova', name: '冰霜爆發', description: '凍結範圍內敵人並造成傷害（範圍隨技能強化成長）', cooldown: 14, params: { radius: 200, damage: 18, freeze: 2.5 } },
    affinityTags: ['magic', 'frost', 'lightning'],
    startWeapons: ['ice_shard', 'fireball', 'lightning'],
    rarity: 'common',
    palette: ['#8f6ad1', '#6a44b0', '#a8e0ff'],
  },
  {
    id: 'gambler_taro',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '賭徒芋頭',
    description: '高風險高報酬。暴擊超高、暴傷驚人，升級可能開出更稀有，也可能翻出詛咒。',
    role: 'gambler',
    baseStats: { maxHp: 96, armor: 0, moveSpeed: 172, damage: 1.0, attackSpeed: 1.0, critChance: 0.18, critDamage: 1.8, pickupRange: 75, regen: 0.3 },
    passive: { description: '升級選項 +25% 機率升一階稀有度，但商店可能混入詛咒選項', effect: 'gamblerLuck' },
    active: { id: 'fateflip', name: '命運輪盤', description: '轉動命運輪盤，四種強力效果之一：骰子風暴轟炸全場／黃金狂熱／幸運爆發／蔬菜庇護', cooldown: 16, params: {} },
    affinityTags: ['gamble', 'crit', 'gold'],
    startWeapons: ['t_dice', 't_cards', 't_coin'],
    rarity: 'common',
    palette: ['#b58fd1', '#8f63b8', '#e0c2f0'],
  },
  {
    id: 'assassin_sprout',
    name: '影忍豆芽',
    description: '吊車尾出身、卻永不放棄的吵鬧忍者。招牌是「影分身」——分出一群分身圍毆，再掌心凝出高速旋轉的「螺旋衝」貼身轟飛敵人；苦無、手裏劍樣樣來。身法快、暴擊爆表，血薄但越戰越勇。',
    role: 'dps',
    baseStats: { maxHp: 72, armor: 0, moveSpeed: 196, damage: 1.05, attackSpeed: 1.22, critChance: 0.24, critDamage: 1.85, pickupRange: 80, regen: 0.2 },
    passive: { description: '不服輸的忍道：暴擊率額外 +8%、暴擊傷害 +30%、迴避 +8%', mods: { critChance: 0.08, critDamage: 0.3, dodge: 0.08 } },
    active: { id: 'charge', name: '瞬身斬', description: '朝拖曳方向瞬身閃現，斬擊路徑上的敵人', cooldown: 6, params: { dist: 320, damage: 30, knockback: 150 } },
    slots: 4,
    exclusiveGear: true,
    slotLabel: '忍術',
    affinityTags: ['crit', 'spread'],
    startWeapons: ['knife', 'nj_rasen', 'nj_clone'],
    unlockCondition: '通關快速模式',
    rarity: 'rare',
    palette: ['#c5e1a5', '#7cb342', '#33691e'],
  },
  {
    id: 'samurai_tomato',
    name: '浪人番茄',
    description: '一臉死魚眼、成天喊累的懶散浪人，腰間就一把不起眼的木刀。平時軟趴趴，真動起手來——那把木刀斬妖除魔，一刀比一刀狠。糖分不足會鬧脾氣，關鍵一刀卻能斃命。',
    role: 'dps',
    baseStats: { maxHp: 84, armor: 1, moveSpeed: 176, damage: 1.35, attackSpeed: 0.95, critChance: 0.1, critDamage: 1.8, pickupRange: 76, regen: 0.3 },
    passive: { description: '死魚眼刀客：暴擊傷害 +40%、近戰傷害 +15%——看起來很閒，一刀要人命', mods: { critDamage: 0.4 } },
    active: { id: 'whirlslash', name: '白夜叉·亂斬', description: '認真起來的一瞬間——旋身爆發木刀亂斬，重創四周敵人並擊退', cooldown: 8, params: { radius: 190, damage: 45, knockback: 200 } },
    slots: 4,
    exclusiveGear: true,
    slotLabel: '刀法',
    affinityTags: ['melee', 'crit', 'pierce'],
    startWeapons: ['s_iai', 'st_sweep', 'st_flurry'],
    rarity: 'rare',
    palette: ['#e2402f', '#a5231b', '#5fae3a'],
  },
  {
    id: 'cactus_thorns',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '反甲仙人掌',
    description: '荊棘坦克。血厚甲高、渾身尖刺——近戰攻擊他的怪物自己也會受傷。移動慢、輸出偏低，但耐打。',
    role: 'tank',
    baseStats: { maxHp: 176, armor: 7, moveSpeed: 158, damage: 0.82, attackSpeed: 0.9, critChance: 0.03, critDamage: 1.5, pickupRange: 70, regen: 0.6 },
    passive: { description: '尖刺反甲：近戰攻擊你的怪物受到反傷——護甲越高反傷越痛（再依傷害成長）', effect: 'thornsReflect' },
    active: { id: 'thornsNova', name: '荊棘爆發', description: '向四周射出尖刺，重傷並擊退周圍敵人，並獲得護盾', cooldown: 10, params: { radius: 190, damage: 34, knockback: 260, shield: 55 } },
    affinityTags: ['thorn', 'melee', 'zone'],
    startWeapons: ['c_gauntlet', 'c_shield', 'c_whip'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#4c9a52', '#2f6b34', '#8bc34a'],
  },
  {
    id: 'monk_tofu',
    name: '武僧豆腐',
    description: '練成拳意通神的武僧。平時連環快拳、氣彈、震地不間斷輸出，每次擊殺都在體內凝聚真氣——真氣攢滿，一記「氣爆拳」轟碎眼前一切。攢得越久、這一拳越痛。',
    role: 'dps',
    baseStats: { maxHp: 100, armor: 1, moveSpeed: 184, damage: 1.1, attackSpeed: 1.2, critChance: 0.08, critDamage: 1.6, pickupRange: 76, regen: 0.4 },
    passive: { description: '真氣凝聚：每次擊殺累積真氣（菁英/Boss 更多，上限 100），氣爆拳消耗全部真氣、氣越多越痛。攻速 +10%、迴避 +5%', mods: { attackSpeed: 0.1, dodge: 0.05 }, effect: 'chiBuild' },
    active: { id: 'chiBurst', name: '氣爆拳', description: '灌注全部真氣轟出一擊——對最近的敵人（及近旁）造成巨傷，真氣越多越痛', cooldown: 5, params: { base: 40, perChi: 2.2, radius: 90, knockback: 200 } },
    slots: 3,
    exclusiveGear: true,
    slotLabel: '技能',
    affinityTags: ['melee', 'chi', 'fist'],
    startWeapons: ['k_fist', 'mk_chi', 'mk_quake'],
    unlockCondition: '通關快速模式',
    rarity: 'rare',
    palette: ['#f5f0e0', '#d4a574', '#e0733a'],
  },
  {
    id: 'durian_spike',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '暴刺榴槤',
    description: '渾身尖刺的中距離刺手。主動技「蓄刺爆發」按住蓄力越久、放開時往全場噴射的尖刺越大越痛，最高 1.5 倍。',
    role: 'dps',
    baseStats: { maxHp: 106, armor: 2, moveSpeed: 172, damage: 1.1, attackSpeed: 1.05, critChance: 0.06, critDamage: 1.6, pickupRange: 76, regen: 0.4 },
    passive: { description: '滿身是刺：範圍效果 +15%、傷害 +8%', mods: { area: 0.15, damage: 0.08 } },
    active: { id: 'spikecharge', name: '蓄刺爆發', description: '按住蓄力（最多 2 秒），放開時往四周噴射尖刺——蓄越久範圍越大、傷害最高 1.5 倍，並留下尖刺區持續傷害', cooldown: 13, params: { radius: 200, maxRadius: 850, damage: 30, knockback: 200, maxHold: 2, zoneDps: 8, zoneDur: 1.5 } },
    affinityTags: ['thorn', 'pierce', 'spread'],
    startWeapons: ['d_thornshot', 'd_barb', 'c_seed'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#f0a83e', '#e0512f', '#4a4258'],
  },
  {
    id: 'hemp_mystic',
    hidden: true, // TODO 舊制（共用池武器）；待重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '迷幻大麻',
    description: '玩弄心智的孢子幻術師。攻擊會噴出迷幻孢子，讓害蟲「嗑到」而神智不清；主動技「迷幻孢子」灑出一片幻覺雲，範圍內的怪物陷入混亂、亂晃且不再攻擊。血薄，靠控場活命。',
    role: 'control',
    baseStats: { maxHp: 88, armor: 0, moveSpeed: 168, damage: 1.12, attackSpeed: 1.0, critChance: 0.05, critDamage: 1.55, pickupRange: 82, regen: 0.3 },
    passive: { description: '孢子沾染：攻擊 15% 機率使敵人陷入迷幻（混亂 2 秒）；範圍效果 +20%', mods: { area: 0.2 }, effect: 'hazeTouch' },
    active: { id: 'hallucinate', name: '迷幻孢子', description: '噴出迷幻孢子雲——範圍內敵人陷入混亂（亂走、不攻擊）並受傷；孢子雲留存數秒持續施加混亂（範圍隨技能強化成長）', cooldown: 15, params: { radius: 190, damage: 14, confuse: 4, cloudDur: 5, cloudRadius: 150 } },
    affinityTags: ['spore', 'zone', 'magic'],
    startWeapons: ['h_spore', 'h_pollen', 'poison_flask'],
    unlockCondition: '通關無盡模式',
    rarity: 'epic',
    palette: ['#6d5aa8', '#e05fd0', '#7cc36a'],
  },
  {
    id: 'kunbao',
    name: '睏寶',
    description: '抱著炸彈睡著的冬瓜寶寶。他不射擊——按技能就在腳下放一顆炸彈（無冷卻，彈數就是儲存次數），等敵人踩進十字爆風、等爆炸引爆下一顆爆炸。站著不動會越睡越沉，炸彈更快爆、火力更大；但一被打醒，一切歸零。爆風不會傷到他，只會把他炸飛。',
    role: 'control',
    baseStats: { maxHp: 124, armor: 3, moveSpeed: 158, damage: 1.0, attackSpeed: 1.0, critChance: 0.04, critDamage: 1.5, pickupRange: 96, regen: 0.6 },
    passive: {
      description: '夢囈引信：不自動射擊，改用主動技能在腳下放炸彈（六個武器模組合成一顆炸彈）。靜止累積睡意、移動流失、受擊歸零——淺眠（40）引信更短、熟睡（80）火力 +1 並持續回血。自己的爆風不造成傷害，只把你炸飛並給 0.25 秒無敵。',
      effect: 'dreamFuse',
    },
    active: {
      id: 'placeBomb', name: '放置炸彈',
      description: '在腳下的格子放一顆炸彈（無冷卻）。技能上的數字＝還能放幾顆：場上每有一顆就少一發，炸掉一顆就回一發。一格只能放一顆。',
      cooldown: 0,
      params: {},
    },
    affinityTags: ['explosive', 'bomb', 'engineer'],
    startWeapons: ['k_crate', 'k_flame', 'k_fuse'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#cfe8c9', '#5aa9e6', '#7bc043'],
  },

  // ============================================================ 致敬型技能英雄（2026-07-11）
  // 機制致敬經典角色原型（動漫/格鬥/靈異），名字與美術全原創——非任何作品的角色。

  {
    id: 'bean_saiyan',
    name: '金剛毛豆',
    description: '會爆氣的戰鬥種族毛豆。越接近力竭、體內鬥氣越猛——生命越低傷害越高。主動技「超覺醒」金光爆發、豆莢炸開，短時間全能力狂飆並暴噴氣浪。招牌武器是貫穿一整列的元氣波。',
    role: 'dps',
    baseStats: { maxHp: 110, armor: 1, moveSpeed: 180, damage: 1.2, attackSpeed: 1.05, critChance: 0.08, critDamage: 1.7, pickupRange: 78, regen: 0.4 },
    passive: { description: '超覺醒鬥氣：生命越低傷害越高（滿血 0 → 力竭時最高 +60%）；暴擊傷害 +15%', mods: { critDamage: 0.15 }, effect: 'superSurge' },
    active: { id: 'surge', name: '超覺醒', description: '金光爆發變身：7 秒內傷害 +60%、攻速 +40%、移速 +20%，並震開四周敵人、回復部分生命', cooldown: 16, params: { duration: 7, dmg: 0.6, atk: 0.4, move: 0.2, heal: 0.15, radius: 190, knockback: 260 } },
    slots: 4,
    exclusiveGear: true,
    slotLabel: '招式',
    affinityTags: ['chi', 'magic', 'pierce'],
    startWeapons: ['be_kiwave', 'be_barrage', 'be_rush'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#8bc34a', '#ffca28', '#33691e'],
  },
  {
    id: 'cabbage_striker',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '鐵腿高麗菜',
    description: '練成鐵腿神功的功夫高麗菜，把每一顆蔬菜都當足球踢。招牌武器是會轉彎追人、命中即爆的烈焰足球。主動技「大力金剛腿」一腳把巨型火球轟成一條貫穿全場的火路。',
    role: 'dps',
    baseStats: { maxHp: 118, armor: 2, moveSpeed: 182, damage: 1.1, attackSpeed: 1.0, critChance: 0.06, critDamage: 1.6, pickupRange: 76, regen: 0.4 },
    passive: { description: '球感絕佳：遠程武器（球）傷害 +12%、範圍效果 +10%', mods: { rangedDamage: 0.12, area: 0.1 } },
    active: { id: 'megaKick', name: '大力金剛腿', description: '一腳轟出巨型火球，沿瞄準方向犁出一條火路——貫穿並擊飛路徑上所有敵人，末端引發大爆炸', cooldown: 11, params: { damage: 40, range: 640, width: 92, knockback: 340, radius: 150 } },
    affinityTags: ['bullet', 'explosive', 'spread'],
    startWeapons: ['ca_football', 'g_shotgun', 'fireball'],
    unlockCondition: '通關標準模式',
    rarity: 'rare',
    palette: ['#66bb6a', '#f5f5f5', '#2e7d32'],
  },
  {
    id: 'chili_boxer',
    name: '拳王辣椒',
    description: '街頭格鬥出身的火爆辣椒。連段是他的命脈——不停命中累積連段量表（一停手就衰退），連得越兇拳頭越痛。主動技「焰昇拳」朝瞄準方向猛竄一記上鉤拳把敵人挑飛；連段滿檔時化為橫掃全場的超必殺。',
    role: 'dps',
    baseStats: { maxHp: 100, armor: 1, moveSpeed: 188, damage: 1.12, attackSpeed: 1.18, critChance: 0.09, critDamage: 1.7, pickupRange: 76, regen: 0.4 },
    passive: { description: '連段流：命中累積連段量表（閒置衰減），連段越高傷害越高（最高 +50%）；連段滿檔時焰昇拳化為橫掃全場的超必殺。攻速 +8%', mods: { attackSpeed: 0.08 }, effect: 'comboMeter' },
    active: { id: 'risingFist', name: '焰昇拳', description: '朝瞄準方向猛竄一記烈焰上鉤拳，重擊並挑飛沿途敵人。連段滿檔（100）時改為橫掃全場的超必殺並清空連段', cooldown: 6, params: { dist: 300, damage: 34, knockback: 340, radius: 120, superRadius: 520, superDmg: 90 } },
    slots: 4,
    exclusiveGear: true,
    slotLabel: '招式',
    affinityTags: ['melee', 'fist', 'chi'],
    startWeapons: ['cf_jab', 'cf_wave', 'cf_hurricane'],
    unlockCondition: '通關快速模式',
    rarity: 'rare',
    palette: ['#e53935', '#ffca28', '#2e7d32'],
  },
  {
    id: 'ghost_shroom',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '幽靈菇',
    description: '從菜園墳頭長出來的亡靈菇，半透明、飄忽、專吸生命。天生迴避高、攻擊吸血。主動技「虛體漂移」化為虛體——短時間無敵、加速穿行，並以怨氣灼傷貼身敵人、大量吸取生命。招牌武器是自動飄向目標的幽冥彈。',
    role: 'control',
    baseStats: { maxHp: 80, armor: 0, moveSpeed: 186, damage: 1.1, attackSpeed: 1.05, critChance: 0.1, critDamage: 1.7, pickupRange: 88, regen: 0.3 },
    passive: { description: '亡靈之軀：迴避 +12%、吸血 +8%', mods: { dodge: 0.12, lifesteal: 0.08 } },
    active: { id: 'phaseShift', name: '虛體漂移', description: '化為虛體：3 秒內無敵、移速 +40%，周身怨氣持續灼傷並吸取貼身敵人的生命', cooldown: 11, params: { duration: 3, move: 0.4, dps: 16, radius: 130, leech: 0.4 } },
    affinityTags: ['magic', 'crit', 'spore'],
    startWeapons: ['gh_wisp', 's_kunai', 'poison_flask'],
    unlockCondition: '通關無盡模式',
    rarity: 'epic',
    palette: ['#b39ddb', '#ede7f6', '#4527a0'],
  },
  {
    id: 'leek_bolt',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '疾雷蔥',
    description: '快到帶殘影的雷屬性青蔥，全場最快、身法飄忽。主動技「雷閃步」瞬間閃現到瞄準點，沿途劈下閃電並連鎖電擊周圍敵人。招牌武器是在敵群間亂跳的雷刃電弧。',
    role: 'dps',
    baseStats: { maxHp: 88, armor: 0, moveSpeed: 200, damage: 1.08, attackSpeed: 1.15, critChance: 0.1, critDamage: 1.65, pickupRange: 80, regen: 0.3 },
    passive: { description: '雷步身法：移速 +8%、迴避 +8%', mods: { moveSpeed: 0.08, dodge: 0.08 } },
    active: { id: 'blink', name: '雷閃步', description: '瞬間閃現到瞄準點，沿途落下閃電並連鎖電擊周圍敵人，抵達時炸開一圈電光', cooldown: 7, params: { dist: 340, damage: 30, radius: 90, chains: 4 } },
    affinityTags: ['lightning', 'magic', 'rapid'],
    startWeapons: ['lk_arc', 'lightning', 'g_smg'],
    unlockCondition: '通關快速模式',
    rarity: 'rare',
    palette: ['#cddc39', '#fff176', '#33691e'],
  },
  {
    id: 'eggplant_vampire',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '血蝠茄',
    description: '化為蝙蝠群的暗夜茄子貴族，靠吸血續命。攻擊天生吸血、擊殺回血。主動技「血祭爆發」轟出猩紅血浪，依命中數大量吸取生命——越多敵人圍著他，回得越猛。招牌武器是彈射的蝠翼鏢。',
    role: 'dps',
    baseStats: { maxHp: 104, armor: 1, moveSpeed: 178, damage: 1.12, attackSpeed: 1.08, critChance: 0.1, critDamage: 1.75, pickupRange: 78, regen: 0.3 },
    passive: { description: '嗜血：吸血 +15%、每次擊殺回 2 生命', mods: { lifesteal: 0.15, lifeOnKill: 2 } },
    active: { id: 'bloodNova', name: '血祭爆發', description: '爆發猩紅血浪重擊四周敵人並擊退，依命中數大量吸取生命回復自己（被越多敵人圍著回越多）', cooldown: 10, params: { radius: 200, damage: 34, knockback: 200, leech: 0.6 } },
    affinityTags: ['crit', 'magic', 'heal'],
    startWeapons: ['vm_fang', 'm_needle', 's_kunai'],
    unlockCondition: '通關無盡模式',
    rarity: 'epic',
    palette: ['#6a1b9a', '#ce93d8', '#4a148c'],
  },
  {
    id: 'avocado_esper',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '念力酪梨',
    description: '額心鑲著念力核的酪梨超能者，用意念扭曲空間。主動技「奇點」在瞄準點造出念力奇點，把周圍敵人強力吸成一團並壓縮傷害——先聚怪、再一鍋端。招牌武器是緩速自動追蹤的念力球。',
    role: 'control',
    baseStats: { maxHp: 96, armor: 1, moveSpeed: 170, damage: 1.1, attackSpeed: 0.98, critChance: 0.06, critDamage: 1.6, pickupRange: 88, regen: 0.35 },
    passive: { description: '念力場：範圍效果 +15%、拾取範圍 +20', mods: { area: 0.15, pickupRange: 20 } },
    active: { id: 'singularity', name: '奇點', description: '在瞄準點造出念力奇點，把範圍內敵人強力吸向中心並造成壓縮傷害——聚怪神技', cooldown: 13, params: { radius: 260, pull: 520, damage: 26 } },
    affinityTags: ['magic', 'frost', 'crit'],
    startWeapons: ['av_orb', 'ice_shard', 'lightning'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#7cb342', '#c5e1a5', '#33691e'],
  },
  {
    id: 'asparagus_blademaster',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '千刃蘆筍',
    description: '一生只練一刀的蘆筍劍聖，快得只剩殘影。主動技「萬刃亂舞」瞬間爆發連環斬，把四周敵人絞成碎片。攻速快、暴傷高，但皮薄，靠身法與爆發吃飯。',
    role: 'dps',
    baseStats: { maxHp: 84, armor: 1, moveSpeed: 190, damage: 1.25, attackSpeed: 1.15, critChance: 0.12, critDamage: 1.85, pickupRange: 76, regen: 0.3 },
    passive: { description: '劍心：暴擊傷害 +20%、攻速 +8%', mods: { critDamage: 0.2, attackSpeed: 0.08 } },
    active: { id: 'bladeDance', name: '萬刃亂舞', description: '瞬間爆發連環斬，對四周敵人造成多段合計的巨量斬擊傷害並擊退', cooldown: 8, params: { radius: 175, hits: 6, damage: 16, knockback: 140 } },
    affinityTags: ['melee', 'crit', 'pierce'],
    startWeapons: ['as_blade', 's_odachi', 'a_shuriken'],
    unlockCondition: '通關快速模式',
    rarity: 'epic',
    palette: ['#7cb342', '#cfd8dc', '#33691e'],
  },
  {
    id: 'corn_gunslinger',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '快槍手玉米',
    description: '西部拔槍最快的玉米神槍手。主動技「神準連射」瞬間自動鎖定並連開一排必中必暴的子彈，指哪打哪。爆發極高、專點硬目標，但單點輸出、不擅面對怪海。',
    role: 'dps',
    baseStats: { maxHp: 90, armor: 0, moveSpeed: 182, damage: 1.1, attackSpeed: 1.2, critChance: 0.14, critDamage: 1.8, pickupRange: 78, regen: 0.25 },
    passive: { description: '神槍手：暴擊率 +10%、遠程傷害 +10%', mods: { critChance: 0.1, rangedDamage: 0.1 } },
    active: { id: 'deadeye', name: '神準連射', description: '瞬間自動鎖定最近的敵人，連開一排必中必暴的子彈（單點爆發極高）', cooldown: 10, params: { shots: 8, damage: 14, range: 520 } },
    affinityTags: ['bullet', 'crit', 'rapid'],
    startWeapons: ['cg_revolver', 'g_sniper', 'a_fan'],
    unlockCondition: '通關快速模式',
    rarity: 'rare',
    palette: ['#ffd54f', '#8d6e63', '#33691e'],
  },
  {
    id: 'mushroom_summoner',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '孢子召喚菇',
    description: '操縱孢子大軍的召喚菇。主動技「孢子軍團」一次布下三座孢子砲塔替你掃射，把陣地變成火力網。本人輸出普通，靠召喚物與陣地戰滾雪球。',
    role: 'engineer',
    baseStats: { maxHp: 108, armor: 2, moveSpeed: 164, damage: 0.95, attackSpeed: 1.0, critChance: 0.04, critDamage: 1.5, pickupRange: 74, regen: 0.4 },
    passive: { description: '菌絲網路：召喚物傷害 +20%、工程傷害 +10%', mods: { minionDamage: 0.2, engineerDamage: 0.1 } },
    active: { id: 'sporeLegion', name: '孢子軍團', description: '一次布下三座自動掃射的孢子砲塔（12 秒），瞬間鋪開一張火力網', cooldown: 15, params: { count: 3, damage: 7, duration: 12, range: 320 } },
    affinityTags: ['engineer', 'summon', 'spore'],
    startWeapons: ['ms_spawner', 'drone', 'mine'],
    unlockCondition: '通關標準模式',
    rarity: 'rare',
    palette: ['#8d6e63', '#ba68c8', '#5d4037'],
  },
  {
    id: 'pitaya_chronos',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '凝時火龍果',
    description: '能扭曲時間流速的火龍果術士。主動技「凝時領域」在瞄準點展開一片幾乎凝滯時間的領域，把裡面的敵人減速到近乎停止並持續受傷——把最兇的一波怪按下暫停鍵。',
    role: 'control',
    baseStats: { maxHp: 92, armor: 0, moveSpeed: 168, damage: 1.12, attackSpeed: 0.98, critChance: 0.05, critDamage: 1.6, pickupRange: 82, regen: 0.3 },
    passive: { description: '時之場：範圍效果 +15%、技能冷卻 -8%', mods: { area: 0.15, cooldown: -0.08 } },
    active: { id: 'timeStop', name: '凝時領域', description: '在瞄準點展開凝時領域：範圍內敵人被極重減速（近乎停止）並持續受傷，留存數秒', cooldown: 14, params: { radius: 240, slow: 0.85, duration: 4, damage: 14 } },
    affinityTags: ['magic', 'frost', 'zone'],
    startWeapons: ['pc_hourglass', 'y_frost', 'ice_shard'],
    unlockCondition: '通關無盡模式',
    rarity: 'epic',
    palette: ['#e91e63', '#7cb342', '#ad1457'],
  },
  {
    id: 'pea_archer',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '神射手豌豆',
    description: '百步穿楊的豌豆神射手，天生多發連射。主動技「箭雨」朝瞄準區域降下一陣密集箭雨，覆蓋一整片區域並持續插箭。遠程壓制與清場一流。',
    role: 'dps',
    baseStats: { maxHp: 86, armor: 0, moveSpeed: 184, damage: 1.08, attackSpeed: 1.1, critChance: 0.09, critDamage: 1.65, pickupRange: 80, regen: 0.3 },
    passive: { description: '連珠箭：投射物 +1、遠程傷害 +8%', mods: { projectiles: 1, rangedDamage: 0.08 } },
    active: { id: 'arrowRain', name: '箭雨', description: '朝瞄準區域降下密集箭雨，覆蓋一整片區域造成大量傷害，並留下持續插箭的箭雨區', cooldown: 11, params: { radius: 220, damage: 30, duration: 2, dps: 8 } },
    affinityTags: ['bullet', 'spread', 'pierce'],
    startWeapons: ['pa_bow', 'g_shotgun', 'c_seed'],
    unlockCondition: '通關標準模式',
    rarity: 'rare',
    palette: ['#66bb6a', '#c5e1a5', '#2e7d32'],
  },
  {
    id: 'garlic_paladin',
    hidden: true, // TODO 重做為 exclusiveGear + 專屬 gear 池後解除隱藏
    name: '聖光大蒜',
    description: '一手聖槌、一身聖光的大蒜聖騎士。血厚甲高，是隊伍的護盾。主動技「聖光爆裂」一擊同時重傷四周敵人並治療周圍所有隊友——攻守一體的前排核心。',
    role: 'support',
    baseStats: { maxHp: 122, armor: 4, moveSpeed: 166, damage: 1.0, attackSpeed: 1.0, critChance: 0.04, critDamage: 1.5, pickupRange: 82, regen: 0.6 },
    passive: { description: '聖光庇佑：護甲 +2、生命回復 +0.4', mods: { armor: 2, regen: 0.4 } },
    active: { id: 'holyNova', name: '聖光爆裂', description: '爆發一圈聖光：重傷並擊退四周敵人，同時治療範圍內所有存活隊友（含自己）', cooldown: 12, params: { radius: 220, damage: 30, heal: 25, knockback: 180 } },
    affinityTags: ['melee', 'support', 'heal'],
    startWeapons: ['gp_hammer', 'heal_orb', 'w_greatsword'],
    unlockCondition: '通關標準模式',
    rarity: 'epic',
    palette: ['#f5f5dc', '#ffd700', '#8d6e63'],
  },
]

export const CHARACTER_MAP = new Map(CHARACTERS.map(c => [c.id, c]))
